validates:
  user:
    maximum_name: 50
    maximum_email: 255
    minimum_pass: 6

search_fields:
  user: ["name", "email", "created_at", "updated_at"]
  location_type: ["name", "created_at", "updated_at"]

controllers:
  admin:
    users:
      pag: 10
    location_types:
      pag: 10
